### ISSUE TITLE
RTD build is broken

### ISSUE THREAD

**Issue by jamadden** [zopefoundation/zope.dublincore#5]
[It looks like](https://readthedocs.org/projects/zopedublincore/builds/5739199/) the package needs to be installed:
```
/home/docs/checkouts/readthedocs.org/user_builds/zopedublincore/checkouts/stable/docs/api.rst:4: WARNING: autodoc: failed to import module u'zope.dublincore.interfaces'; the following exception was raised:
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/zopedublincore/envs/stable/local/lib/python2.7/site-packages/sphinx/ext/autodoc.py", line 551, in import_object
    __import__(self.modname)
ImportError: No module named dublincore.interfaces
```

The `conf.py` doesn't import this, so RTD things the build is green when in reality you just get blank pages.

@tseaver can you please take a look?

**Comment by tseaver** [comment]
Thanks for the report / diagnosis!  I have configured it to install the project.  The [API docs](http://zopedublincore.readthedocs.io/en/latest/api.html) are now populated.

**Comment by jamadden** [comment]
Thank you! 

There are a few other issues open like this at zopefoundation/zope.security#44, zopefoundation/zope.annotation#18 and zopefoundation/zope.password#11 when you have the time and inclination.
